
package views;

import Bo.AerolineasBO;
import conexion.Conexion;
import Entidades.Aerolinea;

import javax.swing.JOptionPane;

/**
 *
 * @author Luis Carlos
 */
public class FrmAerolineas extends javax.swing.JFrame {

    /**
     * Creates new form FrmVuelos
     */
    private AerolineasBO abo = new AerolineasBO();
    
            
    String mensaje = "";
    
    public FrmAerolineas() {
        initComponents();
        idMax();
        setTitle("FORMULARIO AEROLINEAS");
        setLocationRelativeTo(null);
        setResizable(false);
        
               
    }
    
    public void listarAerolinea(){
        abo.listarVuelo(tb_vuelos);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_id = new javax.swing.JLabel();
        txt_id_aerolinea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre_aerolinea = new javax.swing.JTextField();
        label_nombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_vuelos = new javax.swing.JTable();
        btn_salir = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_Modificar1 = new javax.swing.JButton();
        btn_cargar_tabla = new javax.swing.JButton();
        btn_limpiar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_id.setText("ID:");
        jPanel1.add(label_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txt_id_aerolinea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_id_aerolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_aerolineaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id_aerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 250, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("AEROLINEAS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        txt_nombre_aerolinea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_nombre_aerolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_aerolineaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nombre_aerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 250, -1));

        label_nombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_nombre.setText("Nombre:");
        jPanel1.add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        tb_vuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_vuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_vuelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_vuelos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 430, -1));

        btn_salir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, -1, -1));

        btn_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, -1, -1));

        btn_agregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        btn_Modificar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Modificar1.setText("Modificar");
        btn_Modificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modificar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Modificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        btn_cargar_tabla.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_cargar_tabla.setText("Cargar Tabla");
        btn_cargar_tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargar_tablaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cargar_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, -1));

        btn_limpiar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_limpiar2.setText("Limpiar");
        btn_limpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_limpiar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_aerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_aerolineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_aerolineaActionPerformed

    private void txt_nombre_aerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_aerolineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_aerolineaActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
       if (txt_nombre_aerolinea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos de texto");
            
        } else {
            
           Aerolinea aer = new Aerolinea();

        mensaje = abo.eliminarAerolinea(Integer.parseInt(txt_id_aerolinea.getText()));
        JOptionPane.showMessageDialog(null, mensaje);
        
        listarAerolinea();
        limpiar();
            
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed

        if (txt_nombre_aerolinea.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "Llene todos los campos de texto");
            
        } else {
            
         Aerolinea aer = new Aerolinea();
       
        aer.setNombre_aerolinea(txt_nombre_aerolinea.getText());

        mensaje = abo.agregarAerolinea(aer);
        JOptionPane.showMessageDialog(null, mensaje);
        
        listarAerolinea();
        limpiar();
            
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_Modificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modificar1ActionPerformed
        if (txt_nombre_aerolinea.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos de texto");
            
        } else {
            
           Aerolinea aer = new Aerolinea();

        aer.setId_aerolinea(Integer.parseInt(txt_id_aerolinea.getText()));
        aer.setNombre_aerolinea(txt_nombre_aerolinea.getText());
        
       
        mensaje = abo.modificarAerolinea(aer);
        JOptionPane.showMessageDialog(null, mensaje);
        
        listarAerolinea();
        limpiar();
            
        }
    }//GEN-LAST:event_btn_Modificar1ActionPerformed

    private void btn_cargar_tablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargar_tablaActionPerformed
       listarAerolinea();
    }//GEN-LAST:event_btn_cargar_tablaActionPerformed
    public void idMax(){
        txt_id_aerolinea.setText(abo.getMaxID()+"");
    }
    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_limpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar2ActionPerformed
       limpiar();
    }//GEN-LAST:event_btn_limpiar2ActionPerformed

    private void tb_vuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_vuelosMouseClicked
        int seleccion = tb_vuelos.rowAtPoint(evt.getPoint()); 
        
        txt_id_aerolinea.setText(tb_vuelos.getValueAt(seleccion, 0)+"");
        txt_nombre_aerolinea.setText(tb_vuelos.getValueAt(seleccion, 1)+"");
        
        
    }//GEN-LAST:event_tb_vuelosMouseClicked
    
    public void limpiar(){
        txt_id_aerolinea.setText("");
        txt_nombre_aerolinea.setText("");
        
        idMax();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAerolineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAerolineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAerolineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAerolineas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAerolineas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Modificar1;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_cargar_tabla;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar2;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JTable tb_vuelos;
    private javax.swing.JTextField txt_id_aerolinea;
    private javax.swing.JTextField txt_nombre_aerolinea;
    // End of variables declaration//GEN-END:variables
}
