
package views;

import Bo.AvionesBO;
import conexion.Conexion;
import Entidades.Avion;

import javax.swing.JOptionPane;

/**
 *
 * @author Luis Carlos
 */
public class FrmAviones extends javax.swing.JFrame {

    /**
     * Creates new form FrmVuelos
     */
    private AvionesBO avbo = new AvionesBO();
    
            
    String mensaje = "";
    
    public FrmAviones() {
        initComponents();
        idMax();
        setTitle("FORMULARIO AVIONES");
        setLocationRelativeTo(null);
        setResizable(false);
        
               
    }
    
    public void listarAvion(){
        avbo.listarAvion(tb_vuelos);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_id_avion = new javax.swing.JLabel();
        txt_id_avion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_modelo_avion = new javax.swing.JTextField();
        label_modelo_avion = new javax.swing.JLabel();
        txt_id_aerolinea = new javax.swing.JTextField();
        label_id_aerolinea = new javax.swing.JLabel();
        txt_capacidad_pasajeros = new javax.swing.JTextField();
        label_capacidad_pasajeros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_vuelos = new javax.swing.JTable();
        btn_salir = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_verAerolineas = new javax.swing.JButton();
        btn_Modificar1 = new javax.swing.JButton();
        btn_cargar_tabla = new javax.swing.JButton();
        btn_limpiar2 = new javax.swing.JButton();
        btn_agregar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_id_avion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_id_avion.setText("ID Avion");
        jPanel1.add(label_id_avion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txt_id_avion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_id_avion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_avionActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id_avion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 250, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Aviones");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        txt_modelo_avion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_modelo_avion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_modelo_avionActionPerformed(evt);
            }
        });
        jPanel1.add(txt_modelo_avion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 250, -1));

        label_modelo_avion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_modelo_avion.setText("Modelo Avion");
        jPanel1.add(label_modelo_avion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        txt_id_aerolinea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_id_aerolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_aerolineaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id_aerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 250, -1));

        label_id_aerolinea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_id_aerolinea.setText("ID Aerolinea");
        jPanel1.add(label_id_aerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txt_capacidad_pasajeros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_capacidad_pasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_capacidad_pasajerosActionPerformed(evt);
            }
        });
        jPanel1.add(txt_capacidad_pasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 250, -1));

        label_capacidad_pasajeros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_capacidad_pasajeros.setText("Capacidad Pasejeros");
        jPanel1.add(label_capacidad_pasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        tb_vuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_vuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_vuelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_vuelos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 430, -1));

        btn_salir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, -1, -1));

        btn_eliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, -1, -1));

        btn_verAerolineas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_verAerolineas.setText("Ver aerolineas");
        btn_verAerolineas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_verAerolineasMouseClicked(evt);
            }
        });
        btn_verAerolineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verAerolineasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_verAerolineas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        btn_Modificar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Modificar1.setText("Modificar");
        btn_Modificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Modificar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Modificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        btn_cargar_tabla.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_cargar_tabla.setText("Cargar Tabla");
        btn_cargar_tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargar_tablaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cargar_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, -1));

        btn_limpiar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_limpiar2.setText("Limpiar");
        btn_limpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_limpiar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, -1, -1));

        btn_agregar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_agregar1.setText("Agregar");
        btn_agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar1MouseClicked(evt);
            }
        });
        btn_agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_avionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_avionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_avionActionPerformed

    private void txt_modelo_avionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_modelo_avionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_modelo_avionActionPerformed

    private void txt_id_aerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_aerolineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_aerolineaActionPerformed

    private void txt_capacidad_pasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_capacidad_pasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_capacidad_pasajerosActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
       this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
       if (txt_id_aerolinea.getText().isEmpty() || txt_modelo_avion.getText().isEmpty() 
                || txt_capacidad_pasajeros.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos de texto");
            
        } else {
            
         Avion av = new Avion();
       
        
       
        mensaje = avbo.eliminarAvion(Integer.parseInt(txt_id_avion.getText()));
        JOptionPane.showMessageDialog(null, mensaje);
        
        listarAvion();
        limpiar();
            
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_verAerolineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verAerolineasActionPerformed
verAerolineas aerolineas = new verAerolineas();
aerolineas.setVisible(true);
       
    }//GEN-LAST:event_btn_verAerolineasActionPerformed

    private void btn_Modificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Modificar1ActionPerformed
        if (txt_id_aerolinea.getText().isEmpty() || txt_modelo_avion.getText().isEmpty() 
                || txt_capacidad_pasajeros.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos de texto");
            
        } else {
            
            Avion av = new Avion();
         av.setId_avion(Integer.parseInt(txt_id_avion.getText()));
         av.setId_aerolinea(Integer.parseInt(txt_id_aerolinea.getText()));
         av.setModelo_avion(txt_modelo_avion.getText());
         av.setCapacidad_pasajeros(Integer.parseInt(txt_capacidad_pasajeros.getText()));
       
        mensaje = avbo.modificarAvion(av);
        JOptionPane.showMessageDialog(null, mensaje);
        
        listarAvion();
        limpiar();
            
        }
    }//GEN-LAST:event_btn_Modificar1ActionPerformed

    private void btn_cargar_tablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargar_tablaActionPerformed
       listarAvion();
    }//GEN-LAST:event_btn_cargar_tablaActionPerformed
    public void idMax(){
        txt_id_avion.setText(avbo.getMaxID()+"");
    }
    private void btn_verAerolineasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verAerolineasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_verAerolineasMouseClicked

    private void btn_limpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar2ActionPerformed
       limpiar();
    }//GEN-LAST:event_btn_limpiar2ActionPerformed

    private void tb_vuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_vuelosMouseClicked
        int seleccion = tb_vuelos.rowAtPoint(evt.getPoint()); 
        
        txt_id_avion.setText(tb_vuelos.getValueAt(seleccion, 0)+"");
        txt_id_aerolinea.setText(tb_vuelos.getValueAt(seleccion, 1)+"");
        txt_modelo_avion.setText(tb_vuelos.getValueAt(seleccion, 2)+"");
        txt_capacidad_pasajeros.setText(tb_vuelos.getValueAt(seleccion, 3)+"");
        
        
    }//GEN-LAST:event_tb_vuelosMouseClicked

    private void btn_agregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar1MouseClicked

    private void btn_agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar1ActionPerformed
if (txt_id_aerolinea.getText().isEmpty() || txt_modelo_avion.getText().isEmpty() 
                || txt_capacidad_pasajeros.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos de texto");
            
        } else {
            
         Avion av = new Avion();
       
         av.setId_aerolinea(Integer.parseInt(txt_id_aerolinea.getText()));
         av.setModelo_avion(txt_modelo_avion.getText());
         av.setCapacidad_pasajeros(Integer.parseInt(txt_capacidad_pasajeros.getText()));
                
        mensaje = avbo.agregarAvion(av);
        JOptionPane.showMessageDialog(null, mensaje);
        
        listarAvion();
        limpiar();
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar1ActionPerformed
    
    public void limpiar(){
        txt_id_avion.setText("");
        txt_id_aerolinea.setText("");
        txt_modelo_avion.setText("");
        
        txt_capacidad_pasajeros.setText("");
        
        idMax();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAviones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Modificar1;
    private javax.swing.JButton btn_agregar1;
    private javax.swing.JButton btn_cargar_tabla;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar2;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_verAerolineas;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_capacidad_pasajeros;
    private javax.swing.JLabel label_id_aerolinea;
    private javax.swing.JLabel label_id_avion;
    private javax.swing.JLabel label_modelo_avion;
    private javax.swing.JTable tb_vuelos;
    private javax.swing.JTextField txt_capacidad_pasajeros;
    private javax.swing.JTextField txt_id_aerolinea;
    private javax.swing.JTextField txt_id_avion;
    private javax.swing.JTextField txt_modelo_avion;
    // End of variables declaration//GEN-END:variables
}
