/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectolenguajesbasesdedatos;
import Entidades.Cliente;
import Entidades.Reserva;
import conexion.Conexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author fidelitas
 */
public class RegistroReservas extends javax.swing.JFrame {
//Conexion cn;
PreparedStatement ps;
ResultSet rs;
ResultSetMetaData rsm;
DefaultTableModel dtm;
    /**
     * Creates new form NewJFrame
     */
    public RegistroReservas() {
        initComponents();
        setLocationRelativeTo(null);
        Conexion  cn = new Conexion();
        
      ///////////////////Tabla Clientes//////////////////////////
         
      cn.conectar();
    try {
        ps = cn.getConn().prepareStatement("select * from Cliente");
    // se ejecuta el statement
       rs = ps.executeQuery(); 
    // se optienen los datos. 
       rsm = rs.getMetaData();
   
    ArrayList<Object[]> data = new ArrayList<>();
    while (rs.next()){
        Object[] rows=new Object[rsm.getColumnCount()];
        for (int i = 0; i <rows.length; i++){
            rows[i] = rs.getObject(i+1);
        }
        data.add(rows);
    }
    dtm = (DefaultTableModel)this.jTClientes.getModel();
    for (int i = 0; i < data.size(); i++){
        dtm.addRow(data.get(i));
    }
   
   
    }catch (Exception e){    
  JOptionPane.showMessageDialog(null, "error al mostrar datos");
    }
   
     cn.desconectar();
     
   ///////////////////Tabla Vuelos//////////////////////////
   
   cn.conectar();
    try {
        ps = cn.getConn().prepareStatement("select * from Vuelos");
    // se ejecuta el statement
       rs = ps.executeQuery(); 
    // se optienen los datos. 
       rsm = rs.getMetaData();
   
    ArrayList<Object[]> data = new ArrayList<>();
    while (rs.next()){
        Object[] rows=new Object[rsm.getColumnCount()];
        for (int i = 0; i <rows.length; i++){
            rows[i] = rs.getObject(i+1);
        }
        data.add(rows);
    }
    dtm = (DefaultTableModel)this.jTvuelos.getModel();
    
    for (int i = 0; i < data.size(); i++){
        dtm.addRow(data.get(i));
    }
   
   
    }catch (Exception e){    
  JOptionPane.showMessageDialog(null, "error al mostrar datos");
    }
   
     cn.desconectar();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLregistroClientesTitulo = new javax.swing.JLabel();
        jTidvuelo = new javax.swing.JTextField();
        jLnombreCliente = new javax.swing.JLabel();
        jLcorreoCliente = new javax.swing.JLabel();
        jTprecioboleto = new javax.swing.JTextField();
        jLtelefonoCliente = new javax.swing.JLabel();
        jTcantidadBoletos = new javax.swing.JTextField();
        jBingresarCliente = new javax.swing.JButton();
        jBcerrar = new javax.swing.JButton();
        jLnombreCliente1 = new javax.swing.JLabel();
        jTidCliente = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTClientes = new javax.swing.JTable();
        jLregistroClientesTitulo1 = new javax.swing.JLabel();
        jLregistroClientesTitulo2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTvuelos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLregistroClientesTitulo.setText("Registro Reservas");

        jTidvuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidvueloActionPerformed(evt);
            }
        });

        jLnombreCliente.setText("ID_vuelo");

        jLcorreoCliente.setText("Precio boleto");

        jTprecioboleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTprecioboletoActionPerformed(evt);
            }
        });

        jLtelefonoCliente.setText("Cantidad boletos");

        jTcantidadBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcantidadBoletosActionPerformed(evt);
            }
        });

        jBingresarCliente.setText("Reservar");
        jBingresarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBingresarClienteMouseClicked(evt);
            }
        });
        jBingresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBingresarClienteActionPerformed(evt);
            }
        });

        jBcerrar.setText("Cerrar");
        jBcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBcerrarMouseClicked(evt);
            }
        });

        jLnombreCliente1.setText("ID_Cliente");

        jTidCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidClienteActionPerformed(evt);
            }
        });

        jTClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID cliente", "Nombre", "Correo", "Teléfono", "Dirección", "ID País"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTClientes);

        jLregistroClientesTitulo1.setText("Clientes disponibles");

        jLregistroClientesTitulo2.setText("Vuelos disponibles");

        jTvuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID vuelo", "Nombre", "Origen", "ID_Destino", "ID_avion", "id_tipo_asiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTvuelos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLnombreCliente)
                            .addComponent(jLcorreoCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTprecioboleto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTidvuelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLtelefonoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTcantidadBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLnombreCliente1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jBcerrar)
                                .addGap(166, 166, 166)
                                .addComponent(jBingresarCliente))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(jLregistroClientesTitulo1)))
                        .addGap(0, 198, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 223, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLregistroClientesTitulo)
                                .addGap(206, 206, 206))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLregistroClientesTitulo2)
                                .addGap(199, 199, 199))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLregistroClientesTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnombreCliente)
                    .addComponent(jTidvuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcorreoCliente)
                    .addComponent(jTprecioboleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLtelefonoCliente)
                    .addComponent(jTcantidadBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLnombreCliente1)
                    .addComponent(jTidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLregistroClientesTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLregistroClientesTitulo2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcerrar)
                    .addComponent(jBingresarCliente))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTidvueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidvueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidvueloActionPerformed

    private void jTprecioboletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTprecioboletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTprecioboletoActionPerformed

    private void jTcantidadBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcantidadBoletosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcantidadBoletosActionPerformed

    private void jBingresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBingresarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBingresarClienteActionPerformed

    private void jBcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBcerrarMouseClicked
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBcerrarMouseClicked

    private void jBingresarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBingresarClienteMouseClicked
int id_reserva = 1;
int id_vuelo = Integer.parseInt(jTidvuelo.getText());
int precioBoleto = Integer.parseInt(jTprecioboleto.getText());
int cantidadBoletos = Integer.parseInt(jTcantidadBoletos.getText());
int id_Cliente = Integer.parseInt(jTidCliente.getText());

Reserva reserva = new Reserva(id_reserva,id_vuelo,precioBoleto,cantidadBoletos,id_Cliente);
reserva.ingresarReserva();
this.dispose();

//hacer ingreso de cliente en base de datos.
    }//GEN-LAST:event_jBingresarClienteMouseClicked

    private void jTidClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcerrar;
    private javax.swing.JButton jBingresarCliente;
    private javax.swing.JLabel jLcorreoCliente;
    private javax.swing.JLabel jLnombreCliente;
    private javax.swing.JLabel jLnombreCliente1;
    private javax.swing.JLabel jLregistroClientesTitulo;
    private javax.swing.JLabel jLregistroClientesTitulo1;
    private javax.swing.JLabel jLregistroClientesTitulo2;
    private javax.swing.JLabel jLtelefonoCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTClientes;
    private javax.swing.JTextField jTcantidadBoletos;
    private javax.swing.JTextField jTidCliente;
    private javax.swing.JTextField jTidvuelo;
    private javax.swing.JTextField jTprecioboleto;
    private javax.swing.JTable jTvuelos;
    // End of variables declaration//GEN-END:variables
}
